// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4FvWak1QKxAICuLg0NcT9eoHLQtH4As',
    appId: '1:474247250950:web:1716679fd1e6b327d1ef87',
    messagingSenderId: '474247250950',
    projectId: 'kirana-survey',
    authDomain: 'kirana-survey.firebaseapp.com',
    storageBucket: 'kirana-survey.firebasestorage.app',
    measurementId: 'G-W1J8ZB7S8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArpdsda9u45qvHnXytUCG3EL3NHcBbbmo',
    appId: '1:474247250950:android:f266df33c1c30c93d1ef87',
    messagingSenderId: '474247250950',
    projectId: 'kirana-survey',
    storageBucket: 'kirana-survey.firebasestorage.app',
  );
}
